services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000" # 호스트의 8000번 포트 -> 컨테이너의 8000번 포트
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000" # 호스트의 3000번 포트 -> 컨테이너의 3000번 포트
    environment:
      - VITE_API_BASE_URL=http://backend:8000 # 백엔드 컨테이너에 접근
